python main_experiments.py --models allmpnet --poolings all --agg_layers DYNAMIC --save_dir allmpnet_all_dynamic_cl --dynamic_weights_path dynamic_weights_sbert_honest.json && python main_experiments.py --models allmpnet --poolings all --agg_layers UNIVERSAL --save_dir allmpnet_all_universal_cl --dynamic_weights_path dynamic_weights_sbert.json && python main_experiments.py --task_type similarity --models allmpnet --poolings all --agg_layers UNIVERSAL --save_dir allmpnet_all_universal_si --dynamic_weights_path dynamic_weights_sbert.json
python main_experiments.py --models deberta-base --poolings all --agg_layers DYNAMIC --save_dir deberta_all_dynamic_cl --dynamic_weights_path dynamic_weights_deberta_honest.json && python main_experiments.py --models deberta-base --poolings all --agg_layers UNIVERSAL --save_dir deberta_all_universal_cl --dynamic_weights_path dynamic_weights_deberta.json && python main_experiments.py --task_type similarity --models deberta-base --poolings all --agg_layers UNIVERSAL --save_dir deberta_all_universal_si --dynamic_weights_path dynamic_weights_deberta.json
python main_experiments.py --models deberta-base --poolings AVG,AVG+AVG-NS,CLS+AVG+AVG-NS,CLS+AVG,AVG-NS,CLS+AVG-NS --agg_layers IN-TASK,LEAVE-ONE-OUT-SENTEVAL,AVG-SENTEVAL,NLI,LEAVE-ONE-OUT-SENTEVAL-NLI,AVG-ALL --save_dir cl_deberta_cap3_principais_poolings --dynamic_weights_path cap3_dynamic_layers_weights/dynamic_weights_universal_v5.json && python main_experiments.py --task_type similarity --models deberta-base --poolings AVG,AVG+AVG-NS,CLS+AVG+AVG-NS,CLS+AVG,AVG-NS,CLS+AVG-NS --agg_layers IN-TASK,LEAVE-ONE-OUT-SENTEVAL,AVG-SENTEVAL,NLI,LEAVE-ONE-OUT-SENTEVAL-NLI,AVG-ALL --save_dir si_deberta_cap3_principais_poolings --dynamic_weights_path cap3_dynamic_layers_weights/dynamic_weights_universal_v5.json
python cap3_main_classificacao.py --pooling_type avg --base_path final_results_cap3 && python cap3_main_classificacao.py --pooling_type cls --base_path final_results_cap3 && python cap3_main_classificacao.py --pooling_type cls_avg --base_path final_results_cap3

python cap3_main_classificacao.py --model_name answerdotai/ModernBERT-base --pooling_type avg --base_path final_results_cap3 && python cap3_main_classificacao.py --model_name answerdotai/ModernBERT-base --pooling_type cls --base_path final_results_cap3 && python cap3_main_classificacao.py --model_name answerdotai/ModernBERT-base --pooling_type cls_avg --base_path final_results_cap3
python cap3_main_classificacao.py --model_name microsoft/deberta-v3-large --pooling_type avg --base_path final_results_cap3 && python cap3_main_classificacao.py --model_name microsoft/deberta-v3-large --pooling_type cls --base_path final_results_cap3 && python cap3_main_classificacao.py --model_name microsoft/deberta-v3-large --pooling_type cls_avg --base_path final_results_cap3
python cap3_main_classificacao.py --model_name google-bert/bert-base-uncased --pooling_type avg --base_path final_results_cap3 && python cap3_main_classificacao.py --model_name google-bert/bert-base-uncased --pooling_type cls --base_path final_results_cap3 && python cap3_main_classificacao.py --model_name google-bert/bert-base-uncased --pooling_type cls_avg --base_path final_results_cap3
python cap3_main_classificacao.py --model_name FacebookAI/roberta-base --pooling_type avg --base_path final_results_cap3 && python cap3_main_classificacao.py --model_name FacebookAI/roberta-base --pooling_type cls --base_path final_results_cap3 && python cap3_main_classificacao.py --model_name FacebookAI/roberta-base --pooling_type cls_avg --base_path final_results_cap3

(todos) python main_experiments.py --task_type classification --models deberta-base --poolings CLS,AVG,AVG-NS,CLS+AVG,AVG+AVG-NS,CLS+AVG-NS,CLS+AVG+AVG-NS --agg_layers AVG-ALL,AVG-SENTEVAL,IN-TASK,LEAVE-ONE-OUT-SENTEVAL,LEAVE-ONE-OUT-SENTEVAL-NLI,NLI --save_dir final_results_deberta_cl_avg --dynamic_weights_path train_scripts/final_results_cap3/results_microsoft_deberta-v3-base/avg/dynamic_weights_mean.json

(teste) python main_experiments.py --task_type classification --models deberta-base --poolings CLS,AVG,AVG-NS,CLS+AVG,AVG+AVG-NS,CLS+AVG-NS,CLS+AVG+AVG-NS --agg_layers AVG-ALL,LEAVE-ONE-OUT-SENTEVAL-NLI --save_dir final_results_deberta_cl_avg_teste --dynamic_weights_path train_scripts/final_results_cap3/results_microsoft_deberta-v3-base/avg/dynamic_weights_mean.json



#RODANDO
python main_experiments.py --task_type classification --models deberta-base --poolings all --agg_layers IN-TASK,LEAVE-ONE-OUT-SENTEVAL,AVG-SENTEVAL,NLI,LEAVE-ONE-OUT-SENTEVAL-NLI,AVG-ALL --dynamic_weights_path train_scripts/emnlp_classification_weights